### ISSUE TITLE
LED will not light on Pico W

### ISSUE THREAD

**Issue by tngliker** [famiclone6502/DIY_Datalink_Adapter#3]
Hello, Thanks for creating this project. I am attempting to use the Raspberry Pi Pico version of it to communicate with my Datalink 100 watch. I am running the Datalink software in Windows ME with VMware 16. After considerable effort I have managed to get the Datalink software to recognize the Pi as a serial device and give me the "Auto-calibration is successful" message. However, the LED simply does not light up when it's supposed to be sending information. I have checked that the LED is functional with another script. Any help would be appreciated. Thank you!

**Comment by famiclone6502** [comment]
If you're seeing any type of "calibration" message, it sounds like you are still trying to use the CRT monitor to send. The software that comes with the 100 model watch did not support serial adapters. But, you can still download the final official 2.1d version that does from Timex. During the setup wizard, change the output to Serial. You should see a progress bar like the screenshot on my README.md page, and not a bunch of flickering lines when sending. Let me know if I'm on the right track.

**Comment by tngliker** [comment]
Thanks for your reply! The "Auto-calibration is successful" message comes up during the software's tutorial for connecting the notebook adapter. There is an option for using the CRT monitor output instead but I've never selected it nor have I seen the flickering lines from the screen that I remember so fondly holding my wrist up to when I had one of these watches in the 90s. It appears to be recognizing the Pi as the notebook adapter successfully, the LEDs just dont do anything.

**Comment by famiclone6502** [comment]
You wouldn't happen to be using a Pico W would you? I don't have one yet, but I know they changed the method for accessing the LED. Does the code in your working script use pin 25 to blink? 

I would need to update the code for the wireless model, or if they changed the method on newer Picos (or newer firmware?).

In the meantime, if you have a 1k resistor and LED, you may want to try changing the pin # in my code to use that instead. I have a comment in there recommending pin 18.

I hope this helps.

**Comment by tngliker** [comment]
Yes I am using a Pico W so that does explain the issue. I don't have an LED or resistor so I'll just grab a non wireless Pico rather than wait for you to update the code. Thanks so much for your help.

**Comment by famiclone6502** [comment]
I'm glad we were able to figure it out. I will update the README.md page to reflect this incompatibility, and also leave this issue open until I can get my hands on a Pico W. Thanks for bringing this to my attention!

**Comment by famiclone6502** [comment]
I was able to obtain a Pico W, but unfortunately it is unsuitable for this project. When accessing the built-in LED through the Wi-Fi chip, the latency/overhead is too great. However, you can still change the code to use another GPIO pin and connect an external LED+resistor on this model.

**Comment by famiclone6502** [comment]
I've published a version now that simultaneously blinks an external LED if connected to GPIO port 18. This has been tested and works on either model.

**Comment by Shilbo** [comment]
Built a simple docking station that houses the Pico, and the phone, at the right distance and position, whilst also shielding from room lighting. 
![Data Link 1](https://github.com/famiclone6502/DIY_Datalink_Adapter/assets/81716973/34877772-f6e1-48a2-b23d-ee75981dbdba)
![Data link 2](https://github.com/famiclone6502/DIY_Datalink_Adapter/assets/81716973/5b949c03-5ab0-4aec-bd11-b5a0ff898516)
![Data link 3](https://github.com/famiclone6502/DIY_Datalink_Adapter/assets/81716973/98fdf6f5-e50d-48d4-b113-2c663153500a)
Happy to share the DesignSpark file, or the STL, if anyone wants it.

**Comment by famiclone6502** [comment]
> Built a simple docking station that houses the Pico, and the phone, at the right distance and position, whilst also shielding from room lighting. Happy to share the DesignSpark file, or the STL, if anyone wants it.

Wow, this is incredible! Please do share, I would love to add a link to these.

**Comment by Shilbo** [comment]
Thank you. Files for the docking station are at https://github.com/Shilbo/Datalink/
Sorry. New to Github, so not sure how to link properly.

**Comment by famiclone6502** [comment]
> Thank you. Files for the docking station are at https://github.com/Shilbo/Datalink/ Sorry. New to Github, so not sure how to link properly.

Thanks Shilbo! I've added a link to your repository and gave special thanks!

**Comment by Shilbo** [comment]
Great stuff. Thank you. And thanks for creating the project and taking time to post it on Github. Brought my old phone to life again!
