### ISSUE TITLE
New issue: How to make melodys for Timex Datalink 150

### ISSUE THREAD

**Issue by Igor22113377** [famiclone6502/DIY_Datalink_Adapter#5]
Hello. I was playing with the watch software, and i was trying to make some melodys for the watch. I have the software for linux the name of the software is datalink-1.0.0 if someone needs it, i will upload it. It uses SVGA Library.

So, i was playing with the ORGINAL Timex Datalink Software, and the melodys for the Timex Datalink 150 are coded with SPC Format. I think the melodys are 4 bit, so in the SPC File are poliphonic melodys so it uses MIDI format i think.

So - how to make such a melody. Using what? And how to code it for it to work? I dont want any help with uploading it to the watch (At the moment)

**Comment by famiclone6502** [comment]
Sorry, this is not an issue within the scope of this project. I am unable to assist with other issues related to the watch beyond syncing with the laptop adapter clone.

**Comment by Igor22113377** [comment]
> Sorry, this is not an issue within the scope of this project. I am unable to assist with other issues related to the watch beyond syncing with the laptop adapter clone. 

I didn't know where to post this, because Datalink is niche watch, and i don't know how to get as many replies as possible, so i posted the issue right here. If you can't help, that's ok, because there are other users, so you didn't had to close this issue, but i understand. Have a nice day
