### ISSUE TITLE
Can this software work with Pi 4?

### ISSUE THREAD

**Issue by continue47** [famiclone6502/DIY_Datalink_Adapter#6]
Can I run this on a Raspberry Pi 4 if I connect an external LED to it?

**Comment by famiclone6502** [comment]
Only if someone comes up with a way to use a Raspberry Pi 4 with the Arduino IDE. So far, no one has (as far as I know). 
You're welcome to independently re-implement what I have (port) it to ARM Linux in a way that it would work on an RPi 4 and external LED. But, it would be much less effort to purchase an already compatible RPi Pico, drag and drop the .uf2 file, and connect an LED + resistor.
